# Generated by Django 3.2.8 on 2021-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Price per unit')),
                ('amount', models.FloatField(verbose_name='Total filled up amount')),
                ('distance', models.FloatField(verbose_name='Total odometer')),
            ],
        ),
    ]
