# Generated by Django 4.0 on 2022-06-01 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fillup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('equipment', '0002_alter_equipmentuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, validators=[fillup.models.validate_positive], verbose_name='Price per unit')),
                ('amount', models.FloatField(validators=[fillup.models.validate_positive], verbose_name='Total filled up amount')),
                ('distance', models.FloatField(verbose_name='Total odometer')),
                ('addition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tank_full', models.BooleanField(default=True)),
                ('distance_delta', models.FloatField(null=True, verbose_name='Distance delta')),
                ('total_price', models.FloatField(null=True, verbose_name='Total price')),
                ('consumption', models.FloatField(null=True, verbose_name='Consumption')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
