# Generated by Django 3.2.7 on 2021-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Price per unit')),
                ('amount', models.FloatField(verbose_name='Total filled up amount')),
                ('distance', models.FloatField(verbose_name='Total odometer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=32, verbose_name='Register number')),
                ('name', models.TextField(verbose_name='Name of the vehicle')),
            ],
        ),
    ]
