# Generated by Django 4.0 on 2022-06-17 12:03

from django.db import migrations, models
import fillup.models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillup',
            options={'ordering': ['-addition_date']},
        ),
        migrations.AlterField(
            model_name='fillup',
            name='amount',
            field=models.FloatField(validators=[fillup.models.validate_positive], verbose_name='Total filled up amount (litres)'),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='distance',
            field=models.FloatField(verbose_name='Odometer (km)'),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[fillup.models.validate_positive], verbose_name='Price per unit (€/l)'),
        ),
    ]
