# Generated by Django 3.2.7 on 2021-09-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fillup.vehicle'),
            preserve_default=False,
        ),
    ]
