# Generated by Django 3.2.7 on 2021-09-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillup', '0002_fillup_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(choices=[(1, 'Read Only'), (2, 'Driver'), (3, 'Owner')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillup.vehicle')),
            ],
        ),
    ]
