# Generated by Django 3.2.8 on 2021-10-28 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fillup.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillup', '0002_fillup_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillup',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='fillup',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='amount',
            field=models.FloatField(validators=[fillup.models.validate_positive], verbose_name='Total filled up amount'),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[fillup.models.validate_positive], verbose_name='Price per unit'),
        ),
    ]
