# Generated by Django 3.2.8 on 2021-10-28 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0003_auto_20211028_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='addition_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
