# Generated by Django 3.2.7 on 2021-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0004_auto_20210930_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleuser',
            name='role_id',
        ),
        migrations.AddField(
            model_name='vehicleuser',
            name='role',
            field=models.CharField(choices=[('RO', 'Read only'), ('DR', 'Driver'), ('OW', 'Owner')], default='RO', max_length=2),
        ),
    ]
