# Generated by Django 3.2.8 on 2021-10-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillup', '0005_auto_20210930_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RO', 'Read only'), ('DR', 'Driver'), ('OW', 'Owner')], default='RO', max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillup.person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillup.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleUser',
        ),
        migrations.AddField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(through='fillup.VehiclePerson', to='fillup.Vehicle'),
        ),
    ]
