# Generated by Django 3.2.9 on 2021-11-24 18:22

from django.db import migrations, models
import fillup.models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0005_fillup_tank_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='distance_delta',
            field=models.FloatField(null=True, validators=[fillup.models.validate_positive], verbose_name='Distance delta'),
        ),
    ]
