# Generated by Django 3.2.9 on 2021-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0006_fillup_distance_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='distance_delta',
            field=models.FloatField(null=True, verbose_name='Distance delta'),
        ),
    ]
