# Generated by Django 3.2.8 on 2021-10-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0006_auto_20211007_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RO', 'Read only'), ('DR', 'Driver'), ('OW', 'Owner')], default='RO', max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillup.person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillup.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='VehiclePerson',
        ),
        migrations.AlterField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(through='fillup.VehicleUser', to='fillup.Vehicle'),
        ),
    ]
