# Generated by Django 3.2.9 on 2021-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0007_alter_fillup_distance_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='Total price'),
        ),
    ]
