# Generated by Django 3.2.9 on 2021-12-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0008_fillup_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='consumption',
            field=models.FloatField(null=True, verbose_name='Consumption'),
        ),
    ]
