version: "3"

services:
  lopokuluapp:
    build:
      context: .
      dockerfile: development/lopokuluapp.dockerfile
    command: gunicorn lopokulu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app/
    env_file:
      - development/lopokulu.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - lopokulu-dev-data:/var/lib/postgresql/data
    env_file:
      - development/postgres.env

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    env_file:
      - development/adminer.env

  web:
    image: nginx:latest
    volumes:
      - ./development/nginx-templates:/etc/nginx/templates
      - ./static:/srv/www/assets
    ports:
      - 8080:80
    env_file:
      - development/nginx.env
    depends_on:
      - lopokuluapp

volumes:
  lopokulu-dev-data:
