# SPDX-FileCopyrightText: 2021 Jani Lehtinen
# SPDX-FileCopyrightText: 2021 Markus Ijäs
# SPDX-FileCopyrightText: 2021 Markus Murto
#
# SPDX-License-Identifier: CC0-1.0

version: "3.5"

services:
  lopokuluapp:
    image: lopokulu:dev
    container_name: lopokulu_app_1
    build:
      context: .
      target: development
    ports:
      - 8080:8000
    volumes:
      - ./src:/lopokulu/src/
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - lopokulu-dev-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    env_file:
      - .env

volumes:
  lopokulu-dev-data:
