# SPDX-FileCopyrightText: 2021 Jani Lehtinen
# SPDX-FileCopyrightText: 2021 Markus Ijäs
# SPDX-FileCopyrightText: 2021 Markus Murto
#
# SPDX-License-Identifier: CC0-1.0

version: "3"

services:
  lopokuluapp:
    build:
      context: .
      dockerfile: testing/lopokuluapp.dockerfile
    command: /bin/sh -c "/entrypoint.sh"
    volumes:
      - ./src:/src/
      - ./staticfiles:/static/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - lopokulu-dev-data:/var/lib/postgresql/data

  web:
    image: nginx:latest
    volumes:
      - ./testing/nginx-templates:/etc/nginx/templates
      - ./staticfiles:/srv/www/assets
    ports:
      - 8088:80
    depends_on:
      - lopokuluapp

volumes:
  lopokulu-dev-data:
