version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - lopokulu-dev-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lopokuluDev
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  web:
    image: nginx
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80

volumes:
  lopokulu-dev-data:
