version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - lopokulu-dev-data:/var/lib/postgresql/data
    env_file:
      - docker-env/postgres.dev

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    env_file:
      - docker-env/adminer.dev

  web:
    image: nginx:latest
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    ports:
      - 8080:80
    env_file:
      - docker-env/nginx.dev

volumes:
  lopokulu-dev-data:
