// SPDX-FileCopyrightText: 2021 Jani Lehtinen
// SPDX-FileCopyrightText: 2021 Markus Ijäs
// SPDX-FileCopyrightText: 2021 Markus Murto
//
// SPDX-License-Identifier: CC0-1.0

pipeline {
  agent any
  stages {
    stage('Prepare') {
      steps {
        sh 'docker-compose -f docker-compose-testing.yaml up -d --build'
      }
    }

    stage('Test') {
      steps {
        sh 'docker exec lopokulu_app_1 coverage run src/manage.py test src'
      }
    }

    stage('Coverage reports') {
      steps {
        sh 'docker exec lopokulu_app_1 coverage xml'
        sh 'docker cp lopokulu_app_1:/lopokulu/coverage.xml .'
      }
    }

    stage('Cleanup') {
      steps {
        sh 'docker-compose -f docker-compose-testing.yaml down'
      }
    }
  }
  environment {
    DEBUG = 'True'
    POSTGRES_DB = 'lopokulu'
    POSTGRES_PORT = '5432'
    POSTGRES_HOST = 'postgres'
    PGDATA = '/var/lib/postgresql/data/pgdata'
    NGINX_HOST = 'localhost'
    NGINX_PORT = '80'
    POSTGRES_USER = credentials('lopokulu-postgres-user')
    POSTGRES_PASSWORD = credentials('lopokulu-postgres-password')
    SECRET_KEY = credentials('lopokulu-django-secret-key')
  }
}
