# Generated by Django 3.2.8 on 2021-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
