# Generated by Django 4.0 on 2022-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('register_number', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
