# Generated by Django 4.0 on 2022-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuser',
            name='role',
            field=models.CharField(choices=[('READ_ONLY', 'Read only'), ('USER', 'User'), ('ADMIN', 'Administrator')], default='READ_ONLY', max_length=32),
        ),
    ]
