# Generated by Django 4.0 on 2022-06-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
    ]
