# Generated by Django 4.0 on 2022-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='allowed_measurements',
            field=models.JSONField(default=list),
        ),
    ]
