# Generated by Django 4.0 on 2022-06-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_allowed_measurements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
    ]
