# Generated by Django 4.0 on 2022-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(default='BaseMeasurement', max_length=64),
        ),
    ]
