# Generated by Django 4.0 on 2022-05-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_person_is_superuser'),
        ('equipment', '0002_equipmentuser'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
    ]
